MasoniteFramework/masonite

config/database.py

I added support for non-standard database ports to `config/database.py`

Add `port` dictionary key

---

Pipfile

UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

fix warning of psycopg2 getting renamed

---

README.md

As reported on Slack, earlier it pointed to version 2.1 docs.

Fix documenation link

---

masonite/auth/Auth.py
masonite/request.py
tests/core/test_session.py

Closes #193 
Was having issues flashing bytes because it needs to be saved to the session which needed to save to a cookie. Now the request session does not flash anything other than strings

fixed flashing of session when bytes exists

---

src/masonite/helpers/routes.py
src/masonite/request.py
src/masonite/testing/MockRoute.py
tests/core/test_requests.py

Closes #211 
This PR changes how query strings are parsed for Masonite 2.3.
Instead of a url like `/?filter[name]=Joe&filter[user]=bob&email=user@email.com`
parsing to:
```python
{
"filter[name]": "Joe",
"filter[user]": "Bob",
"email": "user@email.com"
}
```
It will now parse into:
```python
{
"email": "user@email.com",
"filter": {
"name": "Joe",
"user": "bob"
}
}
```

improved query parsing

---

.gitignore
Makefile
requirements.txt
setup.py
src/masonite/exception_handler.py
src/masonite/response.py
tests/core/test_response.py

This pull request adds support for returning tuples to set both a response and a status:
```python
def show(self, view: View):
return view.render('some/error/template'), 403
```

added status code tuples in controllers

---

src/masonite/commands/BaseScaffoldCommand.py
src/masonite/commands/JobCommand.py
src/masonite/commands/MailableCommand.py
src/masonite/commands/ProviderCommand.py
src/masonite/commands/ViewCommand.py

This brings consistency in how the classnames are generated for various
craft commands.
Fix #236

Add postfix to craft commands where appropriate.

---

src/masonite/helpers/time.py

There is a small typo in src/masonite/helpers/time.py.
Should read `pendulum` rather than `pendlum`.

Fix simple typo: pendlum -> pendulum

---

src/masonite/drivers/broadcast/BroadcastAblyDriver.py

fixed issue for ably broadcast driver: 'BroadcastConfig key was not found in the container'
exception log:
```
Traceback (most recent call last):
File "/home/abhi/pwork/masonite_projs/todo/.py38env/lib/python3.8/site-packages/masonite/managers/Manager.py", line 77, in create_driver
self.manage_driver = self.container.make(
File "/home/abhi/pwork/masonite_projs/todo/.py38env/lib/python3.8/site-packages/masonite/app.py", line 89, in make
obj = self.resolve(obj, *arguments)
File "/home/abhi/pwork/masonite_projs/todo/.py38env/lib/python3.8/site-packages/masonite/app.py", line 190, in resolve
return obj(*objects)
File "/home/abhi/pwork/masonite_projs/todo/.py38env/lib/python3.8/site-packages/masonite/drivers/broadcast/BroadcastAblyDriver.py", line 18, in __init__
self.config = …
```

fixed issue for ably broadcast driver

---

app/http/controllers/subdirectory/deep/DeepController.py
routes/web.py
src/masonite/routes.py
tests/core/test_routes.py

This adds the namespace parameter to RouteGroup and fixes #226.
One change I'd note:
Prior to this fix, some process (I'm not sure what) tries to find the controllers for all the routes up front. Because Routes are constructed before RouteGroups, this meant that you would get a bunch of "Cannot find controller" messages up front, then the RouteGroup would adjust the namespace and resolve properly. This was misleading, so I therefore moved the print to when you attempt to use the route. This aligns with when the exception is raised, but may make it more difficult to track down malformed routes since the controllers are not reported as malformed up front. 
Perhaps `craft show:routes` could be adjusted to resolve controllers? 
Alternatively -- I just thought of this -- perhaps the _namespace …

Add namespace parameter to RouteGroup Fix/226

---

config/mail.py
src/masonite/drivers/mail/MailSmtpDriver.py

As noted in issue #260 this adds support for making the SMTP login optional. If the login entry is missing, it defaults to True - it requires login just like before.

Allow SMTP without login

---

src/masonite/commands/presets/Preset.py
src/masonite/commands/presets/React.py
src/masonite/commands/presets/Vue.py
tests/presets/test_preset.py
tests/presets/test_react.py
tests/presets/test_vue.py

This will add an empty app.scss to resources/sass when calling `craft preset vue` or `craft preset react`

Add missing app.scss for Vue/React presets

---

src/masonite/commands/InstallCommand.py

**Describe the bug**
By calling `craft new` all required packages will be installed automatically. In general it's a good idea, but this design decision has some drawbacks. In my case the requirements were installed successfully, but the wrong environment was chosen. So I got this consequential error:
```
[CommandNotFound]
Command "key" is not defined.
```
The sub command "key" could not be found, because the command "key" was not registered in this loop:
```python
try:
from wsgi import container  # <----- ImportError in wsgi.py
from cleo import Command
for key, value in container.collect(Command).items():
application.add(value)
except ErrorDuringImport as e:
print(e)
except ImportError:  # <----- Catch and ignore the ImportError
pass
```
This happen, because of some broken imports: …

fix/pip-installation: Fix installation of dependencies by using the Python module of pip

---

src/masonite/drivers/mail/BaseMailDriver.py
src/masonite/drivers/mail/MailLogDriver.py
src/masonite/drivers/mail/MailMailgunDriver.py
src/masonite/drivers/mail/MailSmtpDriver.py
src/masonite/drivers/mail/MailTerminalDriver.py
src/masonite/drivers/mail/Mailable.py
tests/core/test_mail_log_drivers.py
tests/core/test_mail_smtp_driver.py

- Make mail.send_from more consistent. Allow setting the mail from address including the display name.
Supported using:
`mail.send_from('john.smith@example.com')`
`mail.send_from('John Smith <john.smith@example.com>')`
`mail.send_from('john.smith@example.com', 'John Smith')`
- renamed `to_address` to `to_addresses` and is now held as a list of addresses
Supported:
`mail.to('john@example.com')`
`mail.to(['john@example.com'])`
`mail.to(['john@example.com', 'another@example.com'])`

'Mail - mail_from and to_addresses

---

src/masonite/request.py
src/masonite/testing/__init__.py
src/masonite/testing/generate_wsgi.py
tests/core/test_extends.py
tests/core/test_requests.py

If you have a request coming in as a list and then as a dict, `request.all()` currently returns the old list from the previous request. This PR fixes this issue.

Fixed raw_input to reset for each request

---

src/masonite/middleware/GuardMiddleware.py

I noticed the that Guard middleware had the wrong name, so I created this silly pull request to fix it.

Correct the module name

---

src/masonite/request.py
tests/core/test_requests.py

`request.scheme()` http/https
`request.host()` server host
`request.port()` server port
`request.url()` scheme://host:port/path
`request.full_path()` path part of the url
`request.full_url()`  scheme://host:port/path?query-string
`request.query_string()` query-string part

Added request methods to get info of the request

---

src/masonite/exception_handler.py
src/masonite/snippets/exceptions/dump.html

This adds support for passing multiple objects to dd() and having it show all the results. The existing single argument form still works.
I kept the members property since it was in the original exception_handler, but unless I'm missing something it isn't used.
I made some edits to the output. It includes a header showing the number of objects if you dump more than one. I also added separators between them so it is easier to tell where the output for one ends and the next one begins.

Add multiple arg support to dd()

---

src/masonite/routes.py

Ref. discussion in #questions on Slack.
I made a small bypass to allow defining route controllers without a method by performing the following change in https://github.com/MasoniteFramework/masonite/blob/cb6d0d8333c648436425b6fc40f165af36c6a41e/src/masonite/routes.py#L216
```python
self.controller_method = mod[1] if len(mod) == 2 else '__call__'
```
This allows for routes to be defined more similar to Laravel, like this: `GET('/', 'WelcomeController').name('welcome'),` instead of the current: `GET('/', 'WelcomeController@show').name('welcome'),`.
Corresponding controller.
```python
class WelcomeController(Controller):
def __call__(self, request: Request):
return {"message": "Welcome."}
```
I know this is not the correct way use `__call__`, but would you be interested in implementing a …

Route controllers can now be set without a method in routes.

---

src/masonite/commands/presets/Vue3.py
tests/presets/test_vue3.py

Implements part of #370 to upgrade Vue 3 preset dependencies.
The other part is in cookie-cutter repo https://github.com/MasoniteFramework/cookie-cutter/pull/7

Fix/370: Update NPM dependencies
