app/http/middleware/AuthenticationMiddleware.py, app/http/middleware/LoadUserMiddleware.py, bootstrap/start.py, config/middleware.py, docs/Commands/Creating-a-Command.md, docs/Middleware.md
See the Milestones for this release https://github.com/josephmancuso/masonite/milestone/4
=> v0.3.2 Release

.travis.yml, readme.md, requirements.txt, tests/framework/test_get_route.py, tests/framework/test_requests.py, tests/framework/test_validator.py
References: https://github.com/josephmancuso/masonite/issues/17
=> Add Validation Support

config/session.py
For 2.0
Discussion was here: https://github.com/MasoniteFramework/core/pull/119
=> Make session driver default to cookie

readme.md
Signed-off-by: Peng Xiao <xiaoquwl@gmail.com>
=> add requirements for mac installation

.travis.yml
Reference to issue: https://github.com/MasoniteFramework/core/issues/297
See https://github.com/travis-ci/travis-ci/issues/9815
=> add Python 3.7 to .travis.yml

readme.md
Closes https://github.com/MasoniteFramework/core/issues/312
=> remove gittter badge

app/http/middleware/VerifyEmailMiddleware.py, config/middleware.py, databases/migrations/2018_01_09_043202_create_users_table.py
Updated User migration and added middleware.
Relies on XXX PR for core
=> Add Middleware for Email Verification feature

.env-example, config/application.py
This looks like to be obvious but may be I miss something ;)
=> make use of APP_NAME in env

config/auth.py, config/database.py, config/mail.py, config/queue.py, config/session.py, config/storage.py, resources/templates/welcome.html, routes/web.py, tests/framework/test_file_locations.py
cleaned up a bit but really no bad feelings if we keep it as is.
=> cleanup unused imports and whitespace

app/User.py, app/http/controllers/WelcomeController.py, app/http/middleware/AuthenticationMiddleware.py, app/http/middleware/CsrfMiddleware.py, app/http/middleware/LoadUserMiddleware.py, app/http/middleware/VerifyEmailMiddleware.py, bootstrap/start.py, config/application.py, config/auth.py, config/broadcast.py, config/cache.py, config/database.py, config/mail.py, config/middleware.py, config/packages.py, config/providers.py, config/queue.py, config/session.py, config/storage.py, databases/migrations/2018_01_09_043202_create_users_table.py, databases/seeds/database_seeder.py, routes/web.py, wsgi.py
Closes https://github.com/MasoniteFramework/core/issues/468
=> Add pep8 and pep257

masonite/snippets/auth/controllers/PasswordController.py
=> Fix `undefined name view` error.

routes/web.py, src/masonite/auth/Auth.py, src/masonite/commands/AuthCommand.py
Condenses down the route generation and abstracts it into the auth class:
Closes #172
=> slimmed down the routes creation

src/masonite/app.py, tests/core/test_container.py
=> improved app collection

src/masonite/commands/PresetCommand.py, src/masonite/commands/presets/Tailwindcss.py, src/masonite/commands/presets/tailwindcss-stubs/resources/css/app.css, src/masonite/commands/presets/tailwindcss-stubs/resources/js/bootstrap.js, src/masonite/commands/presets/tailwindcss-stubs/tailwind.config.js, src/masonite/commands/presets/tailwindcss-stubs/webpack.mix.js, tests/presets/test_tailwindcss.py
This is a start for adding Tailwind CSS support by porting most of https://github.com/laravel-frontend-presets/tailwindcss
=> Add Tailwind CSS preset

src/masonite/commands/MailableCommand.py
=> updates craft mailable command description

README.md
=> change Python version on README.md

MANIFEST.in
=> Add shared-stubs directory to MANIFEST.in

storage/logs/.gitignore
first commit on this project, i d'ont know if this should go in branch master or 2.3.
=> add gitignore file in storage/logs

src/masonite/helpers/misc.py, src/masonite/request.py, tests/core/test_requests.py, tests/helpers/test_clean_request_input.py
can now decide on if you want to clean quotes when cleaning input
Closes #231
=> added quote cleaning

resources/templates/mail/welcome.html, resources/templates/mail/welcome.txt, src/masonite/drivers/mail/BaseMailDriver.py, src/masonite/drivers/mail/MailMailgunDriver.py, src/masonite/drivers/mail/MailSmtpDriver.py, src/masonite/request.py, src/masonite/routes.py, tests/core/test_extends.py, tests/core/test_mail_base_driver.py, tests/core/test_mail_smtp_driver.py, tests/core/test_mailgun_driver.py, tests/core/test_routes.py
=> Next Minor

config/database.py
Just adding MSSQL to default configuration.
=> Add MSSQL default configuration

config/database.py
With new updates, this changed.
=> Fix ConnectionResolver call

requirements.txt, src/masonite/commands/NewCommand.py, src/masonite/exceptions.py, tests/commands/test_new.py
Implements #342.
This will allow to start project for custom presets/template Masonite projects that we/or the community can maintain.
=> Add crafting project from Git repository

src/masonite/exception_handler.py, src/masonite/providers/RouteProvider.py, src/masonite/testing/TestCase.py, tests/core/test_request_routes.py
Fixes issue where same route on different domains would result in a 404.
Closes #366
=> fixed issue with same route on different domains

src/masonite/helpers/misc.py
#375 fixed `deprecated` decorator
=> fixed `deprecated` decorator

src/masonite/request.py
=> reset query params
